#This is a Simple Game Playes with random number generated by computer

import random

print("Lets play Stone, Paper or SCissors !! ")
computer_guess = random.randint(0,2)

#computer_guess = 0 : stone
#computer_guess = 1: paper
#computer_guess = 2 : Scissors

answer = input(" Are you ready to play ?? ").lower()

if answer != "yes" :
    quit()
else:
    print( "Let's go Yeah !!! ")

while True:
    player_guess = input(" Stone, Paper or Scissors ?? ").lower()

    if player_guess == "stone" && computer_guess == 0 :
        print("its a Tie")
        continue
    elif player_guess == "stone" && computer_guess == 0 :